exports.TinyInit = void 0;
exports.TinyInit = null;
require("DeclarationTiny");
require("DeclarationKatex");
require("DeclarationHtml2Canvas");
require("DeclarationPako");
require("DeclarationUPNG");
require("DeclarationMathquill");
require("PluginTinyMoodle");
require("iEMoodle_fr_dlg");
require("iEMoodle_en_dlg");
require("iEMoodle_it_dlg");
require("iEMoodle_es_dlg");
require("iEMoodle_nl_dlg");
require("PluginTinyMathquill");
require("iEMathquill_fr_dlg");
require("iEMathquill_it_dlg");
require("iEMathquill_en_dlg");
require("iEMathquill_es_dlg");
require("iEMathquill_nl_dlg");
