exports.TinyInit = void 0;
exports.TinyInit = null;
require("DeclarationTiny.js");
require("DeclarationKatex.js");
require("DeclarationHtml2Canvas.js");
require("DeclarationPako");
require("DeclarationUPNG.js");
require("DeclarationMathquill.js");
require("PluginTinyMoodle");
require("tiny/iEMoodle/langs/fr_dlg.js");
require("tiny/iEMoodle/langs/en_dlg.js");
require("tiny/iEMoodle/langs/it_dlg.js");
require("tiny/iEMoodle/langs/es_dlg.js");
require("tiny/iEMoodle/langs/nl_dlg.js");
require("PluginTinyMathquill");
require("tiny/iEMathquill/langs/fr_dlg.js");
require("tiny/iEMathquill/langs/it_dlg.js");
require("tiny/iEMathquill/langs/en_dlg.js");
require("tiny/iEMathquill/langs/es_dlg.js");
require("tiny/iEMathquill/langs/nl_dlg.js");
