exports.EGenreCommande = void 0;
var EGenreCommande;
(function (EGenreCommande) {
  EGenreCommande[(EGenreCommande["ChangerRessource"] = 0)] = "ChangerRessource";
  EGenreCommande[(EGenreCommande["Impression"] = 1)] = "Impression";
  EGenreCommande[(EGenreCommande["Validation"] = 2)] = "Validation";
  EGenreCommande[(EGenreCommande["Aide"] = 4)] = "Aide";
  EGenreCommande[(EGenreCommande["Communication"] = 5)] = "Communication";
  EGenreCommande[(EGenreCommande["ChangerOnglet"] = 6)] = "ChangerOnglet";
  EGenreCommande[(EGenreCommande["AccesMobile"] = 7)] = "AccesMobile";
  EGenreCommande[(EGenreCommande["Accueil"] = 12)] = "Accueil";
  EGenreCommande[(EGenreCommande["Tutoriel"] = 14)] = "Tutoriel";
  EGenreCommande[(EGenreCommande["Twitter"] = 16)] = "Twitter";
  EGenreCommande[(EGenreCommande["CompteEnfant"] = 19)] = "CompteEnfant";
  EGenreCommande[(EGenreCommande["Forum"] = 30)] = "Forum";
  EGenreCommande[(EGenreCommande["CloudIndex"] = 31)] = "CloudIndex";
  EGenreCommande[(EGenreCommande["Videos"] = 32)] = "Videos";
  EGenreCommande[(EGenreCommande["Profil"] = 33)] = "Profil";
  EGenreCommande[(EGenreCommande["ImpressionHTML"] = 34)] = "ImpressionHTML";
  EGenreCommande[(EGenreCommande["changerMembre"] = 35)] = "changerMembre";
})(EGenreCommande || (exports.EGenreCommande = EGenreCommande = {}));
