exports.TradGlossaireOrientation = void 0;
const ObjetTraduction_1 = require("ObjetTraduction");
const TradGlossaireOrientation = ObjetTraduction_1.TraductionsModule.getModule(
	"GlossaireOrientation",
	{
		Orientation: "",
		SpecialitesOrdre: "",
		Option: "",
		PublieLe: "",
		Ressources: {
			LettreEtablissement: "",
			LettreHorsEtablissement: "",
			DispoEtablissement: "",
			DispoHorsEtablissement: "",
			AvisProvisoireCC: "",
			MsgAvisProvisoireCC: "",
			IntentionsFamille: "",
			RecommandationSurVoieNonDemandee: "",
			PropositionCC: "",
			ChoixDefinitifsFamille: "",
			MsgPropositionCC: "",
			PropositionSurVoieNonDemandee: "",
			DecisionRetenue: "",
			MsgDecisionRetenue: "",
			Commentaire: "",
			IntentionsOrientations: "",
			ChoixDefinitifs: "",
			MessageSaisieIndisponible: "",
			DemandeStagePasserelle: "",
			StagePasserellePropose: "",
			IntentionsEtAvisProvisoire: "",
			ChoixEtPropositions: "",
		},
		Bouton: { Supprimer: "", IntentionsOrientation: "", ChoixDefinitifs: "" },
		TitreListe: "",
		ClicChoixOrientation: "",
		Supprimer: "",
		Specialite: "",
		Specialites: {
			TitreListe: "",
			ClicChoixSpecialite: "",
			Supprimer: "",
			UniquementSpecialiteEleve: "",
			AjoutImpossible: "",
			AucuneSpecialiteDisponible: "",
		},
		Options: {
			TitreListe: "",
			ClicChoixOption: "",
			Ajouter: "",
			Supprimer: "",
			AjoutImpossible: "",
			AucuneOptionDisponible: "",
		},
		SaisiePriseEnCompte: "",
		AR: {
			RetourFamilleASaisirAvant: "",
			RetourFamille: "",
			ReponseFamilleASaisirAvant: "",
			ReponseFamilleSaisiePar: "",
			PropositionCCStageAR: "",
			PrisConnaissance: "",
			FamillePrisConnaissance: "",
			Jaccepte: "",
			JeRefuse: "",
			LaFamilleAccepteLaPropositionDuConseilDeClasse: "",
			LaFamilleNAcceptePasLaPropositionEtDemandeUnRDV: "",
			NousAcceptons: "",
			NousAcceptonsSuite: "",
			MsgARProposition: "",
			NousAcceptonsAucune: "",
			NousAcceptonsAucuneSuite: "",
			MsgAttentionSaisieAR: "",
		},
		MsgAucuneOrientation: "",
		AucuneOrientation: "",
		Commentaire: "",
		PublieSurEspaceParent: "",
		ASaisirJusqau: "",
		LanguesOptions: {
			titre: "",
			LV1: "",
			LV2: "",
			Options: "",
			bouton: "",
			TitreListeLV1: "",
			TitreListeLV2: "",
			msgSuppression: "",
			titreMsgErreur: "",
		},
		Voeux: "",
		ARenseignerDuAu: "",
		AvisProvisoireDonneLe: "",
		AvisProvisoire: "",
		RetourLe: "",
		PropositionDonneLe: "",
		Proposition: "",
		ReponseLe: "",
		DecisionRetenueLe: "",
		SupprimerLeVoeux: "",
		OrientationDemandee: "",
		SpecialiteDemandee: "",
		OptionDemandee: "",
		ChoixDesLangues: "",
		RetourAvisConseilClasse: "",
		ReponseDeLaFamille: "",
	},
);
exports.TradGlossaireOrientation = TradGlossaireOrientation;
