exports.TradGlossaireDossierVieScolaire = void 0;
const ObjetTraduction_1 = require("ObjetTraduction");
const TradGlossaireDossierVieScolaire =
	ObjetTraduction_1.TraductionsModule.getModule("GlossaireDossierVieScolaire", {
		TitreFenetreCreationDossier: "",
		TitreFenetreModificationDossier: "",
		Date: "",
		Categorie: "",
		Motif: "",
		InfoEditionMotif: "",
		InfoEditionCategorie: "",
		RespAdmin: "",
		Commentaires: "",
		Contexte: "",
		Lieu: "",
		Victime: "",
		Temoin: "",
		Evenement: "",
		DemandeurRespAdministratif: "",
		Interlocuteur: "",
		ComplementDInformation: "",
		RestreindreVisibiliteDossier: "",
		XPersonnesOntAccesDossier: "",
		MsgMotifDossierObligatoire: "",
		Punition: "",
		Correspondance: "",
		VoirDiscussion: "",
		AjouterElement: "",
		TitreRecapitulatifAnnuel: "",
		TitreDossiers: "",
		AfficherAnneesPrecedentes: "",
		CreerDossier: "",
		MsgConfirmationSupprimerDossier: "",
		MsgConfirmationSupprimerElement: "",
		MsgConfirmationSupprimerPunition: "",
		MsgSuppressionDossierAutreCreateur: "",
		MsgSuppressionElementAutreCreateur: "",
		ParVieScolaire: "",
		ParAutreProfesseur: "",
		DiscussionAvecFamille: "",
		DiscussionAvecEquipePeda: "",
	});
exports.TradGlossaireDossierVieScolaire = TradGlossaireDossierVieScolaire;
