tinymce.addI18n("fr_FR.iEMathquill_dlg", {
	title: "Editeur d'équation",
	Symboles: "Symboles",
	Operateurs: "Opérateurs",
	Relations: "Relations",
	Fleches: "Flèches",
	Divers: "Divers",
	Delimiteurs: "Délimiteurs",
	Formules: "Formules",
	editionLatex: "Edition au format laTeX",
	editionMathquill: "Edition en ligne",
	choixRendu: "Choix du rendu",
	genererImage: "Générer la formule",
	renduVolumineux: "La formule à générer est trop volumineuse.",
});
