exports.StylesChangementLangue = void 0;
exports.StylesChangementLangue = {
	Image_flagBE: "Image_flagBE",
	Image_flagCA: "Image_flagCA",
	Image_flagCH: "Image_flagCH",
	Image_flagDE: "Image_flagDE",
	Image_flagFR: "Image_flagFR",
	Image_flagGB: "Image_flagGB",
	Image_flagIT: "Image_flagIT",
	Image_flagUS: "Image_flagUS",
	Image_flagNL: "Image_flagNL",
	Image_flagMA: "Image_flagMA",
	Image_flagES: "Image_flagES",
	flagConteneur: "flag-conteneur",
	inputWrapper: "input-wrapper",
	asInput: "as-input",
	asSelect: "as-select",
	asLi: "as-li",
	flagImg: "flag-img",
	flagLabel: "flag-label",
};
