exports.StylesDescriptionCalculMoyenne = void 0;
exports.StylesDescriptionCalculMoyenne = {
	MethodeCalculMoyenne: "MethodeCalculMoyenne",
	texteFormule: "texteFormule",
	tableFormule: "tableFormule",
	spanFormule: "spanFormule",
	divFormule: "divFormule",
	titre: "titre",
	fraction: "fraction",
	numera: "numera",
	multipli: "multipli",
	resultat: "resultat",
	complement: "complement",
	margearrondi: "margearrondi",
	separ: "separ",
	bonus: "bonus",
	nonbonus: "nonbonus",
	facult: "facult",
	nonfacult: "nonfacult",
	sur20: "sur20",
	inf10: "inf10",
	mini: "mini",
	maxi: "maxi",
	nonmini: "nonmini",
	nonmaxi: "nonmaxi",
};
