exports.StylesFicheCours = void 0;
exports.StylesFicheCours = {
	FicheCours: "FicheCours",
	ombreCadre: "ombre-cadre",
	ConteneurFiches: "ConteneurFiches",
	SeparateurPremiereFiche: "SeparateurPremiereFiche",
	EnteteDecroche: "EnteteDecroche",
	EnteteDecrocheIcones: "EnteteDecrocheIcones",
	ConteneurCours: "ConteneurCours",
	EnteteCours: "EnteteCours",
	EnteteCoursPeriode: "EnteteCoursPeriode",
	libelleCoursIcone: "libelle-cours-icone",
	EnteteCoursStatut: "EnteteCoursStatut",
	EnteteCoursStatutSansStatut: "EnteteCoursStatutSansStatut",
	EnteteCoursLibelle: "EnteteCoursLibelle",
	VerrouBleu: "VerrouBleu",
	CadreSelection: "CadreSelection",
	contMemo: "cont-memo",
	btnImage: "btnImage",
	BarreOutils: "BarreOutils",
	BoutonOutils: "BoutonOutils",
	Image_FicheCoursBtnAnnulerFiche: "Image_FicheCoursBtnAnnulerFiche",
	Image_FicheCoursBtnSupprimerFiche: "Image_FicheCoursBtnSupprimerFiche",
	Image_FicheCoursBtnDeplacerFiche: "Image_FicheCoursBtnDeplacerFiche",
};
