exports.StylesIEHtmlBtnImage = void 0;
exports.StylesIEHtmlBtnImage = {
	btnImage: "btnImage",
	btnImageDisable: "btnImageDisable",
	btnTooltip: "btnTooltip",
	avecFond: "avecFond",
	btActivable: "bt-activable",
	btnImageIcon: "btnImageIcon",
	colorNeutre: "color-neutre",
	colorRed: "color-red",
	ThemeNeutre: "ThemeNeutre",
	iGreen: "i-green",
	iRed: "i-red",
	btnImageSelection: "btnImageSelection",
	bgRedClaire: "bg-red-claire",
	bgGreenClaire: "bg-green-claire",
	bgOrangeClaire: "bg-orange-claire",
	bgBlueClaire: "bg-blue-claire",
	themeBoutonPrimaire: "themeBoutonPrimaire",
	themeBoutonNeutre: "themeBoutonNeutre",
	mrfiche: "mrfiche",
	icon_star_half: "icon_star_half",
	btBig: "bt-big",
	btLarge: "bt-large",
	btSmall: "bt-small",
	iTop: "i-top",
	btn_icone_deploiement: "btn_icone_deploiement",
	btnBandeau: "btn-bandeau",
};
