exports.StylesInterfacePageAccueil = void 0;
exports.StylesInterfacePageAccueil = {
	AffichagePageAccueil: "AffichagePageAccueil",
	widgetsGlobalContainer: "widgets-global-container",
	emploidutemps: "emploidutemps",
	cdt: "cdt",
	notes: "notes",
	absencesprof: "absencesprof",
	tableaudebord: "tableaudebord",
	agendaetinformations: "agendaetinformations",
	cdc_item_enteteligne: "cdc_item_enteteligne",
	parent: "parent",
	contentContainer: "content-container",
	edtGlobalWrapper: "edt-global-wrapper",
	eleve: "eleve",
	professeur: "professeur",
	accompagnant: "accompagnant",
	tuteur: "tuteur",
	etablissement: "etablissement",
	planning: "planning",
	widgetConteneurPlanning: "widget-conteneur-planning",
	colsWrap1: "cols-wrap1",
	colsWrap2: "cols-wrap2",
	noAbsencesprof: "no-absencesprof",
	noEmploidutemps: "no-emploidutemps",
	noAgendaetinformations: "no-agendaetinformations",
	administrateur: "administrateur",
	primaire: "primaire",
	primdirection: "primdirection",
	primprofesseur: "primprofesseur",
	noCdt: "no-cdt",
	noTableaudebord: "no-tableaudebord",
	primperiscolaire: "primperiscolaire",
	primmairie: "primmairie",
	dotty: "dotty",
	isEdt: "is-edt",
	widget: "widget",
};
