exports.StylesInterfacePageMenus = void 0;
exports.StylesInterfacePageMenus = {
	InterfacePageMenus: "InterfacePageMenus",
	imgIcon: "img-icon",
	colorRed: "color-red",
	halfHeight: "half-height",
	fullHeight: "full-height",
	ctnRepas: "ctn-repas",
	divHorizontal: "div-horizontal",
	disabled: "disabled",
	titreGras: "titre-gras",
	header: "header",
	menuCantine: "menu-cantine",
	ctnVide: "ctn-vide",
	ctnListe: "ctn-liste",
	ctnDate: "ctn-date",
	titreRepas: "titre-repas",
	aliment: "aliment",
	ctnGauche: "ctn-gauche",
	ctnDroite: "ctn-droite",
	ctnAllergenes: "ctn-allergenes",
	ctnLabels: "ctn-labels",
	Image_No_Data: "Image_No_Data",
	imageColonne: "image-colonne",
};
