exports.StylesInterfaceRessources_Eleves = void 0;
exports.StylesInterfaceRessources_Eleves = {
	interfaceRessourcesElevesFlexContainer:
		"interfaceRessourcesElevesFlex-container",
	interfaceRessourcesElevesFlexItem: "interfaceRessourcesElevesFlex-item",
	interfaceRessourcesElevesConteneurVertical:
		"interfaceRessourcesElevesConteneurVertical",
	interfaceRessourcesElevesItemVertical:
		"interfaceRessourcesElevesItemVertical",
	interfaceRessourcesElevesSuperConteneurVertical:
		"interfaceRessourcesElevesSuperConteneurVertical",
	interfaceRessourcesElevesSuperItemVertical:
		"interfaceRessourcesElevesSuperItemVertical",
	ficheWrapper: "fiche-wrapper",
	menuTabsWrapper: "menu-tabs-wrapper",
	contentWrapper: "content-wrapper",
	contenu: "contenu",
	nomPrenom: "nom-prenom",
	item: "item",
	themeFoncee: "theme-foncee",
	libelle: "libelle",
	gris: "gris",
	mt3: "mt-3",
	multiLignes: "multi-lignes",
	hasText: "has-text",
	icon_food: "icon_food",
	regime: "regime",
	wrapper: "wrapper",
	coordonnees: "coordonnees",
	lienCommunication: "lien-communication",
	projets: "projets",
	allergies: "allergies",
	autorisations: "autorisations",
	attestations: "attestations",
	comOk: "com-ok",
	comKo: "com-ko",
	projetsWrapper: "projets-wrapper",
	projetItem: "projet-item",
	libelleContain: "libelle-contain",
	dates: "dates",
	commentaires: "commentaires",
	noWrap: "no-wrap",
	pjContain: "pj-contain",
	itemWrapper: "item-wrapper",
	headContain: "head-contain",
	icon: "icon",
	icon_edit: "icon_edit",
	identiteWrapper: "identite-wrapper",
	photoContain: "photo-contain",
	identiteContain: "identite-contain",
	infosContain: "infos-contain",
	responsabiliteContain: "responsabilite-contain",
	ieChips: "ie-chips",
	text: "text",
	infosWrapper: "infos-wrapper",
	individu: "individu",
	profs: "profs",
	listeIndividus: "liste-individus",
	ObjetFenetre_Espace: "ObjetFenetre_Espace",
	ObjetFenetre_EditionScolarite_racine: "ObjetFenetre_EditionScolarite_racine",
	Fenetre_Cadre: "Fenetre_Cadre",
	Fenetre_Titre: "Fenetre_Titre",
	Fenetre_Espace: "Fenetre_Espace",
	ObjetFenetre_Mobile: "ObjetFenetre_Mobile",
	listeEleves: "liste-eleves",
	avecScroll: "avec-scroll",
};
