exports.StylesInterfaceListeMessagerie = void 0;
exports.StylesInterfaceListeMessagerie = {
	InterfaceListeMessagerie: "InterfaceListeMessagerie",
	ilm_etiqu_disc: "ilm_etiqu_disc",
	fenetre: "fenetre",
	ilm_cont_disc: "ilm_cont_disc",
	listeMessagesDiscussion: "listeMessagesDiscussion",
	ilm_gauche: "ilm_gauche",
	ilm_gauche_entete: "ilm_gauche_entete",
	btnImage: "btnImage",
	ilm_gauche_liste: "ilm_gauche_liste",
	dlse_icon: "dlse_icon",
	icon_plus_cercle: "icon_plus_cercle",
	ilmListeEtiquEntete: "ilm-listeEtiqu-entete",
	listeMessagerie_avertissements: "listeMessagerie_avertissements",
	ilm_droite: "ilm_droite",
	messagerieTitreBandeauMessage: "messagerie-titre-bandeau-message",
	ilm_zoneReponse: "ilm_zoneReponse",
	utilMess_conteneur_visu_messages: "utilMess_conteneur_visu_messages",
	messageVide: "message-vide",
	texte: "texte",
	ilm_zone_saisie: "ilm_zone_saisie",
	ilm_selec_pjs: "ilm_selec_pjs",
	ilm_liste_pjs: "ilm_liste_pjs",
	ilm_brouillon_transfert: "ilm_brouillon_transfert",
	ilm_saisie_pied: "ilm_saisie_pied",
	ilm_pied_dest: "ilm_pied_dest",
	ilm_pied_droite: "ilm_pied_droite",
	ilm_messageInfo: "ilm_messageInfo",
	info: "info",
	ilm_pied_btns: "ilm_pied_btns",
	ieEllipsis: "ie-ellipsis",
	ObjetFenetre_Espace: "ObjetFenetre_Espace",
};
