exports.StylesInterfaceDernieresNotes = void 0;
exports.StylesInterfaceDernieresNotes = {
	InterfaceDernieresNotes: "InterfaceDernieresNotes",
	listeContain: "liste-contain",
	detailContain: "detail-contain",
	ZoneDetailsNotes: "Zone-DetailsNotes",
	infosNote: "infos-note",
	headerIcon: "header-icon",
	commentNote: "comment-note",
	commentaire: "commentaire",
	details: "details",
	eval: "eval",
	detailsNotes: "details-notes",
	icon_comment: "icon_comment",
	detailsPj: "details-pj",
	btnMethodeCalcul: "btnMethodeCalcul",
	ListeDernieresNotes: "ListeDernieresNotes",
	moyennePromo: "moyenne-promo",
	icon_star: "icon_star",
	titreService: "titre-service",
	noteDevoir: "note-devoir",
	evalDevoir: "eval-devoir",
	navPrecSuiv: "nav-prec-suiv",
};
