exports.StylesInterfacePageSaisieAbsences_Cours = void 0;
exports.StylesInterfacePageSaisieAbsences_Cours = {
	PageSaisieAbsenceCours: "PageSaisieAbsenceCours",
	tableAbsenceTitre: "tableAbsenceTitre",
	tableAbsenceEleve: "tableAbsenceEleve",
	tableAbsenceCorps: "tableAbsenceCorps",
	trAbsenceAjoutEleve: "trAbsenceAjoutEleve",
	tableAbsenceTitreNbEleves: "tableAbsenceTitreNbEleves",
	tableAbsenceTitreClasses: "tableAbsenceTitreClasses",
	protectedContain: "protected-contain",
	publiColor: "publi-color",
	tableAbsenceLigneSelectionne: "tableAbsenceLigneSelectionne",
	ligneHaut: "ligneHaut",
	ligneBas: "ligneBas",
	ligneCote: "ligneCote",
	asThWrapper: "as-th-wrapper",
	libelle: "libelle",
	tableAbsenceAvecRecap: "tableAbsenceAvecRecap",
	tableAbsenceCorpsCellule: "tableAbsenceCorpsCellule",
	tableAbsenceCorpsCelluleCoche: "tableAbsenceCorpsCelluleCoche",
	tableAbsenceCorpsCelluleRetard: "tableAbsenceCorpsCelluleRetard",
	tableAbsenceCorpsCelluleTexte: "tableAbsenceCorpsCelluleTexte",
	tableAbsenceEleveAbsentDernierCours: "tableAbsenceEleveAbsentDernierCours",
	tableAbsenceEleveEstAttendu: "tableAbsenceEleveEstAttendu",
	tableAbsenceEleveSortiePeda: "tableAbsenceEleveSortiePeda",
	tableAbsenceRecap: "tableAbsenceRecap",
	tableAbsenceObsNonLue: "tableAbsenceObsNonLue",
	tableAbsenceCorpsCelluleInactive: "tableAbsenceCorpsCelluleInactive",
	tableAbsenceCorpsCelluleVerrouille: "tableAbsenceCorpsCelluleVerrouille",
	tableAbsenceCorpsCelluleInactiveVieSco:
		"tableAbsenceCorpsCelluleInactiveVieSco",
	fixAncienneFeuilleAppel: "fix-ancienne-feuille-appel",
	grilleHoraire: "grille-horaire",
	globalFeuilleAppel: "global-feuille-appel",
	feuilleAppelGauche: "feuille-appel-gauche",
	edtEleve: "edt-eleve",
	edtGauche: "edt-gauche",
	feuilleAppelContainer: "feuille-appel-container",
	gridEleve: "grid-eleve",
};
