exports.StylesLivretScolaire = void 0;
exports.StylesLivretScolaire = {
	livretscolaireMain: "livretscolaire-main",
	pfmp_section: "pfmp_section",
	pfmp_titre: "pfmp_titre",
	pfmp_info: "pfmp_info",
	pfmp_nbrSem: "pfmp_nbrSem",
	pfmp_sep: "pfmp_sep",
	pfmp_appr: "pfmp_appr",
	pfmp_sansInfo: "pfmp_sansInfo",
	pfmp_exp_appr: "pfmp_exp_appr",
	pfmp_exp_synthese: "pfmp_exp_synthese",
	pfmp_exp_radio: "pfmp_exp_radio",
	pfmp_exp_detail: "pfmp_exp_detail",
	pfmp_exp_pied: "pfmp_exp_pied",
	avecCopier: "avecCopier",
	pfmp_exp_auteur: "pfmp_exp_auteur",
	DonneesListe_FicheLivretScolaire: "DonneesListe_FicheLivretScolaire",
	dl_fls_Jauge: "dl_fls_Jauge",
	livretscolaire: "livretscolaire",
	lsEspace: "ls-espace",
	lsSectionTitre: "ls-section-titre",
	lsTitre: "ls-titre",
	lsMrfiche: "ls-mrfiche",
	lsCorps: "ls-corps",
	lsChoix: "ls-choix",
};
