exports.StylesMoteurRDV = void 0;
exports.StylesMoteurRDV = {
	InterfaceRDV: "InterfaceRDV",
	listeRdv: "liste-rdv",
	detailRdv: "detail-rdv",
	messageVide: "message-vide",
	lienCommunication: "lien-communication",
	zoneMessageLarge: "zone-message-large",
	messagesComplementaires: "messages-complementaires",
	messageEtat: "message-etat",
	messageAction: "message-action",
	rdvResume: "rdv-resume",
	rdvIntitule: "rdv-intitule",
	rdvTitre: "rdv-titre",
	InterfaceDetailRDV: "InterfaceDetailRDV",
	rdvContent: "rdv-content",
	section: "section",
	sujet: "sujet",
	creneau: "creneau",
	btnWrapper: "btn-wrapper",
	ObjetMenuCtxMixte: "ObjetMenuCtxMixte",
	FenetreEditionRDV: "FenetreEditionRDV",
	contenuRDV: "contenuRDV",
	fieldContain: "field-contain",
	creneauxProposes: "creneauxProposes",
	ieBtnselecteur: "ie-btnselecteur",
	dateCreneau: "date-creneau",
	inputWrapper: "input-wrapper",
	listeCreneaux: "liste-creneaux",
	chipsContain: "chips-contain",
	legendContain: "legend-contain",
	legendTitre: "legend-titre",
	legendItem: "legend-item",
	icon: "icon",
	asterisque: "asterisque",
};
