exports.StylesObjetDiscussion_Mobile = void 0;
exports.StylesObjetDiscussion_Mobile = {
	ObjetDiscussion_Mobile: "ObjetDiscussion_Mobile",
	utilMess_conteneur_visu_messages: "utilMess_conteneur_visu_messages",
	navheader: "navheader",
	btnImage: "btnImage",
	nav: "nav",
	retour: "retour",
	odm_header_libelle: "odm_header_libelle",
	headerTitre: "header-titre",
	messagerieTitreBandeauMessage: "messagerie-titre-bandeau-message",
	selectDiscussion: "selectDiscussion",
	selectDiscussionNonLu: "selectDiscussionNonLu",
	comboDisc: "combo-disc",
	odm_contenu: "odm_contenu",
	ObjetFenetre_Mobile: "ObjetFenetre_Mobile",
	odm_exercice: "odm_exercice",
	odm_messages: "odm_messages",
	odm_selectModeleAlerte: "odm_selectModeleAlerte",
	ieCombo: "ie-combo",
	contenteditable_index: "contenteditable_index",
	creation: "creation",
	odm_pj: "odm_pj",
	odm_pj_image: "odm_pj_image",
	odm_cbExercice: "odm_cbExercice",
	odm_pied_saisie: "odm_pied_saisie",
	commandes: "commandes",
	odm_pied_pj: "odm_pied_pj",
	themeBoutonPrimaire: "themeBoutonPrimaire",
	ieBouton: "ieBouton",
	boutonCarre: "bouton-carre",
	ieBtnContImgImg: "ieBtnContImg-img",
	odm_TransmettreDir_TableauDeBord: "odm_TransmettreDir_TableauDeBord",
	odmContenuReponse: "odm-contenu-reponse",
	chipsDest: "chips-dest",
	labelDestinataire: "labelDestinataire",
	odm_messagefooter: "odm_messagefooter",
};
