exports.StylesObjetCentraleNotifications = void 0;
exports.StylesObjetCentraleNotifications = {
	ObjetCentraleNotifications: "ObjetCentraleNotifications",
	sc_article: "sc_article",
	cn_section: "cn_section",
	cnHeader: "cn-header",
	cn_section_lu: "cn_section_lu",
	cn_compteurTotal: "cn_compteurTotal",
	_ObjetFenetreNotifications_Mobile_racine:
		"_ObjetFenetreNotifications_Mobile_racine",
	cn_flechegauche: "cn_flechegauche",
	btnImage: "btnImage",
	btnImageIcon: "btnImageIcon",
	cn_fermeture: "cn_fermeture",
	cn_liste_notifs: "cn_liste_notifs",
	cn_scroll: "cn_scroll",
	cn_scroll_inactif: "cn_scroll_inactif",
	cb_contenu_scroll: "cb_contenu_scroll",
	cn_imgAucuneNouvelleNotif: "cn_imgAucuneNouvelleNotif",
	image_centrale_notification: "image_centrale_notification",
	cn_section_titre: "cn_section_titre",
	cn_section_btnLu: "cn_section_btnLu",
	icon_eye_open: "icon_eye_open",
	sc_article_histo: "sc_article_histo",
	sc_article_action: "sc_article_action",
	sc_article_gauche: "sc_article_gauche",
	cn_etiquette_jour: "cn_etiquette_jour",
	icon_calendrier_aujourdhui: "icon_calendrier_aujourdhui",
	cn_etiquette_sep: "cn_etiquette_sep",
	sc_article_contenu: "sc_article_contenu",
	sc_article_contenu_titre: "sc_article_contenu_titre",
	sc_article_contenu_titre_avecBtn: "sc_article_contenu_titre_avecBtn",
	sc_article_contenu_bold: "sc_article_contenu_bold",
	notifMembreExclu: "notif-membre-exclu",
	sc_datePied: "sc_datePied",
	sc_btnCoin: "sc_btnCoin",
	cn_section_secSecurite: "cn_section_secSecurite",
	cnHeaderTexte: "cn-header-texte",
	cn_section_secAdministration: "cn_section_secAdministration",
	cn_section_secMessagerie: "cn_section_secMessagerie",
	cn_section_secMesInformations: "cn_section_secMesInformations",
	cn_section_secPeriscolaire: "cn_section_secPeriscolaire",
	cn_section_secForum: "cn_section_secForum",
	cn_section_secPartenaires: "cn_section_secPartenaires",
	cn_section_secSignature: "cn_section_secSignature",
	cn_section_secEmploiDuTemps: "cn_section_secEmploiDuTemps",
	cn_section_secAutres: "cn_section_secAutres",
};
