exports.StylesObjetListe_Mobile = void 0;
exports.StylesObjetListe_Mobile = {
	ObjetListe: "ObjetListe",
	DonneesListe_SuiviStage: "DonneesListe_SuiviStage",
	skin_flatDesign: "skin_flatDesign",
	liste_btnentete: "liste_btnentete",
	listeTotaleFd: "liste-totale-fd",
	listePied: "liste-pied",
	liste_scroll: "liste_scroll",
	liste_rechercheTexte: "liste_rechercheTexte",
	collection: "collection",
	collectionHeader: "collection-header",
	collectionItem: "collection-item",
	liste_sansBordureD: "liste_sansBordureD",
	withAction: "with-action",
	withActionSimple: "with-action-simple",
	liste_cellule_div: "liste_cellule_div",
	liste_cellule_div_depl: "liste_cellule_div_depl",
	liste_cellule_cb: "liste_cellule_cb",
	liste_cellule_total: "liste_cellule_total",
	liste_surligneur_edition: "liste_surligneur_edition",
	liste_separateur_boutons: "liste_separateur_boutons",
	liste_boutons: "liste_boutons",
	btnFloat: "btn-float",
	liste_messageVide: "liste_messageVide",
	Image_No_Data: "Image_No_Data",
};
