exports.StylesObjetSaisieCodePIN = void 0;
exports.StylesObjetSaisieCodePIN = {
	ObjetSaisieCodePIN: "ObjetSaisieCodePIN",
	scp_zone: "scp_zone",
	scpEtape: "scp-etape",
	scp_inputActif: "scp_inputActif",
	textPin: "text-pin",
	scp_ecarteur_flex: "scp_ecarteur_flex",
	scp_messagePin: "scp_messagePin",
	icon_ok: "icon_ok",
	icon_remove: "icon_remove",
	btPinOublie: "bt-pin-oublie",
	scpVisuPin: "scp-visu-pin",
	disabled: "disabled",
	scpVisuPinLabel: "scp-visu-pin-label",
	scpVisuPinImage: "scp-visu-pin-image",
	scpBlocsPin: "scp-blocs-pin",
	scpPIN: "scp-PIN",
	active: "active",
	scp_boutons: "scp_boutons",
	scpValider: "scp-valider",
	scp_btnclear: "scp_btnclear",
	scp_btnvalider: "scp_btnvalider",
	scpReinitPIN: "scp-reinitPIN",
	scpLinkPied: "scp-link-pied",
};
