exports.StylesObjetFenetre_Edition = void 0;
exports.StylesObjetFenetre_Edition = {
	ObjetFenetre_Edition: "ObjetFenetre_Edition",
	ObjetFenetre_Edition_Contenu: "ObjetFenetre_Edition_Contenu",
	datesContain: "dates-contain",
	rounded: "rounded",
	btPjUnique: "bt-pj-unique",
	commentaire: "commentaire",
	asDatePicker: "as-date-picker",
	asInput: "as-input",
	libelleContain: "libelle-contain",
	libellePj: "libelle-pj",
	ieChips: "ie-chips",
	textareamaxWrapper: "textareamax-wrapper",
	tam_counter: "tam_counter",
	sansCommentaire: "sansCommentaire",
	zoneBas: "zone-bas",
	btnConteneur: "btn-conteneur",
	navheader: "navheader",
	noBg: "no-bg",
	flecheNav: "fleche-nav",
	asTitre: "as-titre",
	separateurHaut: "separateur-haut",
	ocb_bouton: "ocb_bouton",
	mlLarge: "ml-large",
};
