exports.StylesObjetFenetre_EvenementPeriodicite = void 0;
exports.StylesObjetFenetre_EvenementPeriodicite = {
	FenetreEvenement: "FenetreEvenement",
	defTxt: "def-txt",
	likeSpan: "like-span",
	blocHoraire: "bloc-horaire",
	opacityLow: "opacity-low",
	ctnTime: "ctn-time",
	ctnSwitch: "ctn-switch",
	blocDate: "bloc-date",
	blocOuvre: "bloc-ouvre",
	divider: "divider",
	blocSelecteurPeriodicite: "bloc-selecteur-periodicite",
	blocQuotidienne: "bloc-quotidienne",
	blocHebdomadaire: "bloc-hebdomadaire",
	ctnHaut: "ctn-haut",
	ctnListeJours: "ctn-liste-jours",
	blocMensuelleAbsolue: "bloc-mensuelle-absolue",
	ctnBas: "ctn-bas",
	blocMensuelleRelatif: "bloc-mensuelle-relatif",
	ctn: "ctn",
	flexBetween: "flex-between",
	inputNbr: "input-nbr",
};
