exports.StylesObjetBoutonFlottant = void 0;
exports.StylesObjetBoutonFlottant = {
	hasFloatBtnBottom: "has-float-btn-bottom",
	floatingBtnPosition: "floating-btn-position",
	icon: "icon",
	tiny: "tiny",
	small: "small",
	medium: "medium",
	large: "large",
	extraLarge: "extra-large",
	onOff: "on-off",
	vTop: "v-top",
	floatGlobalConteneur: "float-global-conteneur",
	subFloatMenu: "sub-float-menu",
	vBottom: "v-bottom",
	floatBtnConteneur: "float-btn-conteneur",
	vMiddle: "v-middle",
	asButton: "as-button",
	hCenter: "h-center",
	primary: "primary",
	more: "more",
	shown: "shown",
	disabled: "disabled",
	iconOnly: "icon-only",
	command: "command",
	ThemeMobilePN: "ThemeMobilePN",
	ThemeMobileHP: "ThemeMobileHP",
};
