exports.StylesObjetGrillePN = void 0;
exports.StylesObjetGrillePN = {
	ObjetGrille: "ObjetGrille",
	RecreationsDureeGrille: "RecreationsDureeGrille",
	GrilleNonInverse: "GrilleNonInverse",
	GrilleInverse: "GrilleInverse",
	VoileCours: "VoileCours",
	VoileCoursNonObligDispenseEleve: "VoileCoursNonObligDispenseEleve",
	EtiquetteCours: "EtiquetteCours",
	Image_PublieGrille: "Image_PublieGrille",
	etiquetteDuree_cours: "etiquetteDuree_cours",
	etiquetteDuree_coursMarque: "etiquetteDuree_coursMarque",
	etiquetteAucunEleve: "etiquette-aucun-eleve",
	grille_piedRessLibre: "grille_piedRessLibre",
	grille_avecAction: "grille_avecAction",
	PiedHoraireScroll: "PiedHoraireScroll",
	dispoPrioriteTexte: "dispo-priorite-texte",
	hintCoursSortiePedagogique: "hintCoursSortiePedagogique",
	hcsp_titre: "hcsp_titre",
	hcsp_contenu: "hcsp_contenu",
	hcsp_titreMemo: "hcsp_titreMemo",
	hcsp_memo: "hcsp_memo",
	hcsp_separateur: "hcsp_separateur",
};
