exports.StylesObjetFenetre_Mobile = void 0;
exports.StylesObjetFenetre_Mobile = {
	ObjetFenetre_Mobile: "ObjetFenetre_Mobile",
	heightMax: "height-max",
	couleurMenuDark: "couleur-menu-dark",
	FormSaisie: "FormSaisie",
	ofmDesign: "ofm-design",
	content: "content",
	Fenetre_Titre: "Fenetre_Titre",
	ieTitre: "ie-titre",
	iconic: "iconic",
	btnImage: "btnImage",
	navigationContain: "navigation-contain",
	avecScroll: "avec-scroll",
	withoutPadding: "without-padding",
	wrapperContenu: "wrapper-contenu",
	Fenetre_Contenu: "Fenetre_Contenu",
	menuTabsWrapper: "menu-tabs-wrapper",
	ficheWrapper: "fiche-wrapper",
	sectionContent: "section-content",
	noLine: "no-line",
	ieTitreCouleur: "ie-titre-couleur",
	publicTeam: "public-team",
	labelPj: "label-pj",
	iecb: "iecb",
	Fenetre_Bas: "Fenetre_Bas",
	composeBas: "compose-bas",
	sticky: "sticky",
	inputField: "input-field",
	ObjetFenetre_MobileOverlay: "ObjetFenetre_Mobile-overlay",
	hide: "hide",
};
