exports.StylesObjetBlocBillet = void 0;
exports.StylesObjetBlocBillet = {
	ibfaMain: "ibfa-main",
	ObjetListeBlogs: "ObjetListeBlogs",
	ContentPrincipal: "ContentPrincipal",
	filtreActu: "filtre-actu",
	objetFiltre: "objet-filtre",
	FiltresPourModerateur: "FiltresPourModerateur",
	FiltreAuteur: "FiltreAuteur",
	FiltreDates: "FiltreDates",
	FiltreDatesDu: "FiltreDatesDu",
	FiltreDatesAu: "FiltreDatesAu",
	ArticleBillet: "ArticleBillet",
	nonPublie: "nonPublie",
	headerBillet: "header-billet",
	titreBillet: "titre-billet",
	zoneBtnActions: "zone-btn-actions",
	icon_edt_permanence: "icon_edt_permanence",
	ContenuBillet: "ContenuBillet",
	zoneDocs: "zone-docs",
	RedacteursBillet: "RedacteursBillet",
	photos: "photos",
	listeVignettes: "liste-vignettes",
	vignette: "vignette",
	InformationPhotoRedacteur: "InformationPhotoRedacteur",
	zoneBtnsCommentaires: "zone-btns-commentaires",
	CommentairePlusRecent: "CommentairePlusRecent",
	vignetteBlog: "vignetteBlog",
	ArticleCommentaireBillet: "ArticleCommentaireBillet",
	estMien: "estMien",
	estAModerer: "estAModerer",
	EtatCommentaire: "EtatCommentaire",
	warn: "warn",
	ok: "ok",
	notOK: "notOK",
};
