exports.StylesPageOffresStages = void 0;
exports.StylesPageOffresStages = {
	PageOffreStageConteneur: "PageOffreStage-conteneur",
	interface_affV: "interface_affV",
	conteneurGauche: "conteneur-gauche",
	liste_zone: "liste_zone",
	detailOffre: "detail-offre",
	detailoffrestage: "detailoffrestage",
	filtreConteneur: "filtre-conteneur",
	inputField: "input-field",
	periode: "periode",
	recherche: "recherche",
	sujet: "sujet",
	enLigne: "en-ligne",
	fieldsWrapper: "fields-wrapper",
	listeOffres: "liste-offres",
	offrePourvu: "offre-pourvu",
	BandeauFiltre: "Bandeau-filtre",
	bandeauNom: "bandeau-nom",
	filtreConteneurMobile: "filtre-conteneur-mobile",
	champsFiltre: "champs-filtre",
	dureeStage: "duree-stage",
	semaine: "semaine",
};
