exports.StylesWidgetEdtJournalier = void 0;
exports.StylesWidgetEdtJournalier = {
	widget: "widget",
	edt: "edt",
	edtJournalier: "edtJournalier",
	classe: "classe",
	etablissement: "etablissement",
	demipension: "demipension",
	stage: "stage",
	listeCours: "liste-cours",
	greyed: "greyed",
	titre_jour: "titre_jour",
	containerCours: "container-cours",
	containerEtiquette: "container-etiquette",
	containerHeures: "container-heures",
	traitMatiere: "trait-matiere",
	priorite1: "priorite-1",
	priorite2: "priorite-2",
	priorite3: "priorite-3",
	estRetenue: "est-retenue",
	libelleCours: "libelle-cours",
	enCours: "en-cours",
	coursAnnule: "cours-annule",
	enStage: "en-stage",
	enEntreprise: "en-entreprise",
	exclusionEtablissement: "exclusion-etablissement",
	exclusionDemipension: "exclusion-demipension",
	exclusionClasse: "exclusion-classe",
	eleveAbsent: "eleve-absent",
	demiPension: "demi-pension",
	recreation: "recreation",
	pasDeCours: "pas-de-cours",
	listeBoutons: "liste-boutons",
};
